### PR TITLE
add: added http layer for the account actions (get, delete, update)

### LINKED ISSUE #119: Create http layer for user options
Create separate functions for communication with proper endpoints. 
- Remove Account
- Change Password
- ~~Change Username~~
- Change Email

### PR DESCRIPTION
**Pull request by kpagacz**
I tested it with the below code and the usual development environment:
```js
import { registerUser, deleteUser, getUserDetails, updateUser } from "./src/httpLayers/accountActions.http.js";

console.dir(await registerUser("to_delete", "deletepass", "delete@gmail.com"));

let user = await updateUser("to_delete", { email: "new3delete@gmail.com" });
console.dir(user);
user = await updateUser("to_delete", { password: "deletepassword2" });
console.dir(user);

await deleteUser("to_delete");
```

Closes #119 #158

### CODE REVIEW

**Comment by karolkozlo** [comment]
Please update import of registerUser function in RegisterPage

**Comment by kpagacz** [comment]
IMport updated, conflicts resolved, this is ready for rereview

**Comment by karolkozlo** [comment]
When i try run frontend, i see this
problem

**Comment by karolkozlo** [comment]
Cannot log in after changing password

**Review by karolkozlo — APPROVED** [review]
Everything is fine now

**Pull request merged**
