### PR TITLE
[84_WofInput]

### LINKED ISSUE #84: Create WofInput component
Component used to display inputs with validations.
Should contain:
- Title (from prop)
- Input with value (from prop) and styles for validation
- Small error #54 that will display error message (from prop)
Should do:
- Dynamic data change with the v-model on input
- Data emitting with each change

### PR DESCRIPTION
**Pull request by karolkozlo**
[add] New WofInput component
[add] Styling for WofInput component

closes #84

### CODE REVIEW

**Comment by karolkozlo** [comment]
I tested it with this code in App.vue

`<template>
  <main>
    <div class="main-wrapper">
      <router-view msg="This is a basic frontend"></router-view>
      <wof-input name="Test" type="text" :initValue="email" @change="updateEmail" :error="emailErrorMessage"></wof-input>
    </div>
    <wof-footer/>
  </main>
</template>

<script>
import WofFooter from './components/WofFooter.vue';
import WofInput from './components/WofInput.vue';

export default {
  components: { WofFooter, WofInput },
  name: "App",
  data() {
    return {
      email: 'Hehe@gmail.com',
      emailErrorMessage: ''
    }
  },
  methods: {
    updateEmail(value) {
      this.emailErrorMessage = '';
      this.email = value;
      if(!this.email.includes('@')) {
        this.emailErrorMessage = 'Email is not valid - no @';
      }
    }
  }
};
</script>`

**Comment by kpagacz** [comment]
Does it make sense to have an indication that this is an input field?
image
Right now it doesn't even have an outline and nothing suggests this can be clicked and the value changed. If you are short on ideas, then maybe one of those:
* bottom border
* outline
* some kind of shadow/shading
We could also pimp out the styling on this thing but I guess it can wait until we are done with the core functionality of the app.

**Comment by karolkozlo** [comment]
@kpagacz 
Why are you using this input on white background? This design was created with a non-white background in mind. Look on Figma.
As for the error, I can change it.

**Comment by kpagacz** [comment]
I used your example, the background is from there.

**Comment by kpagacz** [comment]
The shading is much better now (but only when active) :)
image

anyway, seems good enough for me

**Review by kpagacz — APPROVED** [review]

**Pull request merged**
