### PR TITLE
add(docker-compose): added a docker compose file for a database instance

### PR DESCRIPTION
**Pull request by kpagacz**
* added a docker-compose file to run a mysql database instance

To test:
* install docker-compose (comes with Docker Desktop on Windows, on MacOS and Linux need to install separately)
* navigate to the new directory
* run
```bash
docker-compose --file development-env.yml up -d 
```
* the instance of mySQL database should run on port 3306.

I found it pretty useful when I was testing out the sequelize code.

### CODE REVIEW

**Comment by kpagacz** [comment]
```
 docker run --name mysql-db -p 3306:3306 -e MYSQL_DATABASE='db' -e MYSQL_USER=wof -e MYSQL_PASSWORD=wof -e MYSQL_ROOT_PASSWORD=wof mysql:latest
```

**Review by kpagacz — COMMENTED** [review]
Needs README with the comment and the code.

**Comment by kpagacz** [comment]
I will add the README tomorrow

**Comment by kpagacz** [comment]
I updated the readmes, @mwiech99

**Review by robert10290 — APPROVED** [review]

**Pull request merged**
