### PR TITLE
devops: added nginx to docker-compose

### PR DESCRIPTION
**Pull request by kpagacz**
Set up an nginx container, added it to docker-compose and created a workflow to automatically build and publish the nginx image

### CODE REVIEW

**Comment by kpagacz** [comment]
To test it out:
```
docker-compose -f docker-compose-environments\development-env.yml up
```
and test out if the connection between the frontend and the backend works without changing the base URL of the axios instance, i.e. if the frontend connection to backend works out of the box.

**Review by mwiech99 — DISMISSED** [review]
Good job! I would just ask you to extend readme and change the frontend port.

**Comment by kpagacz** [comment]
The workflow needs some work as well for now.

**Comment by kpagacz** [comment]
> Good job! I would just ask you to extend readme and change the frontend port.

Expanded README, changed the port and also added a dependency. The workflow probably needs some fixing up but it's not crucial at the moment.

**Review by karolkozlo — APPROVED** [review]

**Pull request merged**
